# Generated by Django 2.0.2 on 2018-03-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('course_num', models.CharField(max_length=10)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lectures.Career')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lectures.Category')),
            ],
        ),
        migrations.CreateModel(
            name='DayTimeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.CharField(max_length=5)),
                ('upper_unit', models.FloatField()),
                ('lower_unit', models.FloatField()),
                ('components', models.ManyToManyField(to='lectures.Category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.Course')),
                ('professors', models.ManyToManyField(to='lectures.Professor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lectures.Room')),
                ('times', models.ManyToManyField(to='lectures.DayTimeField')),
            ],
        ),
        migrations.CreateModel(
            name='YearAndSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lectures.Major'),
        ),
        migrations.AddField(
            model_name='course',
            name='year_and_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lectures.YearAndSemester'),
        ),
    ]
