# Generated by Django 2.0.2 on 2018-03-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='sessions',
            new_name='sections',
        ),
    ]
