# Generated by Django 2.0.2 on 2018-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timetable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='_default',
            field=models.BooleanField(default=False),
        ),
    ]
