# Generated by Django 2.0.2 on 2018-04-09 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_timetable__default'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
